-- Add registration fields to investors table
ALTER TABLE investors
ADD COLUMN IF NOT EXISTS email TEXT,
ADD COLUMN IF NOT EXISTS job_title TEXT,
ADD COLUMN IF NOT EXISTS website TEXT,
ADD COLUMN IF NOT EXISTS linkedin TEXT,
ADD COLUMN IF NOT EXISTS aum TEXT,
ADD COLUMN IF NOT EXISTS check_size TEXT,
ADD COLUMN IF NOT EXISTS focus TEXT,
ADD COLUMN IF NOT EXISTS notes TEXT;
